### ISSUE TITLE
View wireframes don't match schema/timeline

### ISSUE THREAD

**Issue by rglassett** [akanshmurthy/healthbook#3]
You have messages and notifications in your wireframe, but no details on how these will be implemented. It's also unclear what's going on with "Overview / Family / Doctors / etc. / etc." in the profile sidebar. Are these groups?

The news feed wireframe also shows features that aren't outlined elsewhere: reposts, likes, posts including both text and images. Plan this out in advance. Will you have a likes table? For multimedia posts, are images attached automatically for any contained URL, or is there a form for attaching the image?

**Comment by akanshmurthy** [comment]
Good point- I will update my proposal with all the relevant info this weekend. I think for messages, I'd like to hear the websockets lightning talk but otherwise, I've read about a gem in Rails along with this link: http://josephndungu.com/tutorials/gmail-like-chat-application-in-ruby-on-rails.

The Overview/Family/Doctors will all be part of the profile. Items in a form that will be in-line editable. 

Good point. I think I'll keep it simple and just have posts (text and photo) for now as all of those features require other people to be able to view the posts and right now only the user can view his/her own posts. A bonus feature is to allow doctors to view the posts but that might not be part of the MVP if I can't get to it.
